gerenciador_tarefas/app/urls.py
from django.urls import path
from .views.tarefa_views import *
from .views.usuario_views import *

urlpatterns = [
    path('listar_tarefas/', listar_tarefas, name="listar_tarefas"),
    path('cadastrar_tarefas/', cadastrar_tarefas, name="cadastrar_tarefas"),
    path('editar_tarefas/<int:id>', editar_tarefas, name="editar_tarefas"),
    path('remover_tarefa/<int:id>', remover_tarefa, name="remover_tarefa"),
    path('cadastrar_usuario/', cadastrar_usuario, name="cadastrar_usuario"),
    path('logar_usuario/', logar_usuario, name="logar_usuario"),
    path('deslogar_usuario/', deslogar_usuario, name="deslogar_usuario"),
]

gerenciador_tarefas/gerenciador_tarefas/urls.py
"""rotas da aplicacao"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

gerenciador_tarefas/app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = {
        ('A', 'Alta'),
        ('N', 'Normal'),
        ('B', 'Baixa'),
    }
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

gerenciador_tarefas/app/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario', )
        fields = '__all__'

gerenciador_tarefas/app/views/tarefa_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_services
# gerenciao as requisicoes do projeto
# comunicao entre todas as etapas, meio de campo
# Create your views here.

@login_required()
def listar_tarefas(request):
    tarefas = tarefa_services.listar_tarefas(request.user)
    return render(request, "tarefas/listar_tarefas.html", {"tarefas": tarefas})

@login_required()
def cadastrar_tarefas(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                                 prioridade=prioridade, usuario=request.user)
            tarefa_services.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, "tarefas/form_tarefa.html", {"form_tarefa": form_tarefa})

@login_required()
def editar_tarefas(request, id):
    tarefa_bd = tarefa_services.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Nao permitido")
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data["titulo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        tarefa_services.editar_tarefa(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, "tarefas/form_tarefa.html", {"form_tarefa": form_tarefa})

@login_required()
def remover_tarefa(request, id):
    tarefa_bd = tarefa_services.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Nao permitido")
    if request.method == "POST":
        tarefa_services.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {"tarefa": tarefa_bd})

gerenciador_tarefas/app/views/usuario_views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def cadastrar_usuario(request):
    if request.method == "POST":
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_tarefas')
    else:
        form_usuario = UserCreationForm()
    return render(request, 'usuarios/form_usuario.html', {"form_usuario": form_usuario})
    """passa como parametro pra ser usado"""

def logar_usuario(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'As credenciais do usuario estao incorretas')
            return redirect('logar_usuario')
    else:
        form_login = AuthenticationForm()
    return render(request, 'usuarios/login.html', {"form_login": form_login})

def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

gerenciador_tarefas/app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Teste</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Gerenciador de Tarefas - TreinaWeb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas </a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Logout </a>
      </li>
    </ul>
  </div>
</nav>
    <main class="container">
        {% block conteudo %}

        {% endblock conteudo %}
    </main>
</body>
</html>

gerenciador_tarefas/app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}
<div class="card mb-3">
        <div class="card-header">
            Tem certeza, que deseja remover a tarefa abaixo?
        </div>
        <div class="card-body">
            <h5 class="card-title">{{tarefa.titulo}}</h5>
            <p class="card-text">{{tarefa.descricao}}</p>
            <hr>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
            </form>
        </div>
    </div>
{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}

<form method="post">

    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.titulo.erros }}
        <label>Titulo:</label>
        {{form_tarefa.titulo|addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.descricao.erros }}
        <label>Descricao:</label>
        {{form_tarefa.descricao|addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.data_expiracao.erros }}
        <label>Data de expiracao:</label>
        {{form_tarefa.data_expiracao|addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.prioridade.erros }}
        <label>Prioridade:</label>
        {{form_tarefa.prioridade|addclass:'form-control'}}
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar">
    </div>
</form>

{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}
    <h1>Listagem de tarefas</h1>
    {% for tarefa in tarefas  %}
    <div class="card mb-3">
        <div class="card-header">
            {{ tarefa.get_prioridade_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{tarefa.titulo}}</h5>
            <p class="card-text">{{tarefa.descricao}}</p>
            <hr>
            <a href="{% url 'editar_tarefas' tarefa.id %}"> Alterar tarefa </a>
            <a href="{% url 'remover_tarefa' tarefa.id %}"> Remover tarefa </a>
        </div>
    </div>
    {% endfor %}
<a href="{% url 'cadastrar_tarefas' %}"> <input type="button" class="btn btn-primary mb-3" value="Cadastrar tarefa!"></a>
{% endblock conteudo %}

gerenciador_tarefas/app/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form method="post">
    {% csrf_token %}


    <div class="form-group">
        {{form_usuario.username.errors}}
        <label>Username: </label>
        {{form_usuario.username|addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{form_usuario.password1.errors}}
        <label>Senha: </label>
        {{form_usuario.password1|addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{form_usuario.password2.errors}}
        <label>Confirme a senha: </label>
        {{form_usuario.password2|addclass:'form-control'}}
    </div>

    <div class="form-group">
        <input type="submit" value="Cadastrar" class="btn btn-primary">
    </div>
</form>
{% endblock conteudo %}

gerenciador_tarefas/app/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block conteudo %}

<form method="post">
    <div class="form-group">
        {% csrf_token %}
        {% for message in messages %}
            <div class="alert alert-danger">
                {{message}}
            </div>
        {% endfor %}
        <label> Nome de usuario: </label>
        {{form_login.username|addclass:'form-control'}}
    </div>
    <div class="form-group">
        <label> Senha: </label>
        {{form_login.password|addclass:'form-control'}}
    </div>
    <div class="form-group">
        <input type="submit" value="Logar" class="btn btn-primary">
    </div>
</form>

{% endblock conteudo %}